const quotes = [
  "The greatest glory in living lies not in never falling, but in rising every time we fall. — Nelson Mandela",
  "The purpose of our lives is to be happy. — Dalai Lama",
  "Life is what happens when you're busy making other plans. — John Lennon",
  "Get busy living or get busy dying. — Stephen King",
  "You only live once, but if you do it right, once is enough. — Mae West",
  "In three words I can sum up everything I've learned about life: it goes on. — Robert Frost",
  "To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment. — Ralph Waldo Emerson",
  "Life is really simple, but we insist on making it complicated. — Confucius",
  "The only impossible journey is the one you never begin. — Tony Robbins",
  "The best way to predict your future is to create it. — Abraham Lincoln",
  "You must be the change you wish to see in the world. — Mahatma Gandhi",
  "The only limit to our realization of tomorrow is our doubts of today. — Franklin D. Roosevelt",
  "Success is not final, failure is not fatal: It is the courage to continue that counts. — Winston Churchill",
  "To live is the rarest thing in the world. Most people exist, that is all. — Oscar Wilde",
  "Life is short, and it is up to you to make it sweet. — Sarah Louise Delany",
  "The unexamined life is not worth living. — Socrates",
  "You do not find the happy life. You make it. — Camilla E. Kimball",
  "The only way to do great work is to love what you do. — Steve Jobs",
  "Believe you can and you're halfway there. — Theodore Roosevelt",
  "The journey of a thousand miles begins with one step. — Lao Tzu",
  "In the end, it's not the years in your life that count. It's the life in your years. — Abraham Lincoln",
  "Life is either a daring adventure or nothing at all. — Helen Keller",
  "To love and be loved is to feel the sun from both sides. — David Viscott",
  "Life is either a great adventure or nothing. — Helen Keller",
  "It does not do to dwell on dreams and forget to live. — J.K. Rowling",
  "You only live once, but if you do it right, once is enough. — Mae West",
  "The greatest wealth is to live content with little. — Plato",
  "The purpose of life is not to be happy. It is to be useful, to be honorable, to be compassionate, to have it make some difference that you have lived and lived well. — Ralph Waldo Emerson",
  "Life isn’t about finding yourself. Life is about creating yourself. — George Bernard Shaw",
  "The greatest wealth is to live content with little. — Plato",
  "To live is the rarest thing in the world. Most people exist, that is all. — Oscar Wilde",
  "Life is short, and it is up to you to make it sweet. — Sarah Louise Delany",
  "Live in the sunshine, swim the sea, drink the wild air. — Ralph Waldo Emerson",
  "The purpose of our lives is to be happy. — Dalai Lama",
  "You miss 100% of the shots you don’t take. — Wayne Gretzky",
  "I think, therefore I am. — René Descartes",
  "I have not failed. I've just found 10,000 ways that won't work. — Thomas Edison",
  "The only limit to our realization of tomorrow is our doubts of today. — Franklin D. Roosevelt",
  "Do what you can, with what you have, where you are. — Theodore Roosevelt",
  "Life is what happens when you're busy making other plans. — John Lennon",
  "The purpose of life is not to be happy. It is to be useful, to be honorable, to be compassionate, to have it make some difference that you have lived and lived well. — Ralph Waldo Emerson",
  "Success is not final, failure is not fatal: It is the courage to continue that counts. — Winston Churchill",
  "Life is short, and it is up to you to make it sweet. — Sarah Louise Delany",
  "You must be the change you wish to see in the world. — Mahatma Gandhi",
  "To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment. — Ralph Waldo Emerson",
  "The only way to do great work is to love what you do. — Steve Jobs",
  "Believe you can and you're halfway there. — Theodore Roosevelt",
  "The journey of a thousand miles begins with one step. — Lao Tzu",
  "In the end, it's not the years in your life that count. It's the life in your years. — Abraham Lincoln",
  "The only impossible journey is the one you never begin. — Tony Robbins",
  "The best way to predict your future is to create it. — Abraham Lincoln",
  "You do not find the happy life. You make it. — Camilla E. Kimball",
  "Life is either a daring adventure or nothing at all. — Helen Keller",
  "To love and be loved is to feel the sun from both sides. — David Viscott",
  "It does not do to dwell on dreams and forget to live. — J.K. Rowling",
  "You only live once, but if you do it right, once is enough. — Mae West",
  "The greatest wealth is to live content with little. — Plato",
  "The purpose of life is not to be happy. It is to be useful, to be honorable, to be compassionate, to have it make some difference that you have lived and lived well. — Ralph Waldo Emerson",
  "Life isn’t about finding yourself. Life is about creating yourself. — George Bernard Shaw",
  "The greatest wealth is to live content with little. — Plato",
  "To live is the rarest thing in the world. Most people exist, that is all. — Oscar Wilde",
  "Live in the sunshine, swim the sea, drink the wild air. — Ralph Waldo Emerson",
  "The purpose of our lives is to be happy. — Dalai Lama",
  "You miss 100% of the shots you don’t take. — Wayne Gretzky",
  "I think, therefore I am. — René Descartes",
  "I have not failed. I've just found 10,000 ways that won't work. — Thomas Edison",
  "The only limit to our realization of tomorrow is our doubts of today. — Franklin D. Roosevelt",
  "Do what you can, with what you have, where you are. — Theodore Roosevelt",
  "Life is what happens when you're busy making other plans. — John Lennon",
  "The purpose of life is not to be happy. It is to be useful, to be honorable, to be compassionate, to have it make some difference that you have lived and lived well. — Ralph Waldo Emerson",
  "Success is not final, failure is not fatal: It is the courage to continue that counts. — Winston Churchill",
  "Life is short, and it is up to you to make it sweet. — Sarah Louise Delany",
  "You must be the change you wish to see in the world. — Mahatma Gandhi",
  "To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment. — Ralph Waldo Emerson",
  "The only way to do great work is to love what you do. — Steve Jobs",
  "Believe you can and you're halfway there. — Theodore Roosevelt",
  "The journey of a thousand miles begins with one step. — Lao Tzu",
  "In the end, it's not the years in your life that count. It's the life in your years. — Abraham Lincoln",
  "The only impossible journey is the one you never begin. — Tony Robbins",
  "The best way to predict your future is to create it. — Abraham Lincoln",
  "You do not find the happy life. You make it. — Camilla E. Kimball",
  "Life is either a daring adventure or nothing at all. — Helen Keller",
  "To love and be loved is to feel the sun from both sides. — David Viscott",
  "It does not do to dwell on dreams and forget to live. — J.K. Rowling",
  "You only live once, but if you do it right, once is enough. — Mae West",
  "The greatest wealth is to live content with little. — Plato",
  "The purpose of life is not to be happy. It is to be useful, to be honorable, to be compassionate, to have it make some difference that you have lived and lived well. — Ralph Waldo Emerson",
  "Life isn’t about finding yourself. Life is about creating yourself. — George Bernard Shaw",
  "The greatest wealth is to live content with little. — Plato",
  "To live is the rarest thing in the world. Most people exist, that is all. — Oscar Wilde",
  "Live in the sunshine, swim the sea, drink the wild air. — Ralph Waldo Emerson",
  "The purpose of our lives is to be happy. — Dalai Lama",
  "You miss 100% of the shots you don’t take. — Wayne Gretzky",
];
const button = document.getElementById("generate");
const quotesElement = document.getElementById("quotes"); // Fix the element selection

button.addEventListener("click", generateQuotes);

function generateQuotes() {
  const index = Math.floor(Math.random() * quotes.length); // Use quotes.length
  quotesElement.textContent = quotes[index]; // Display the quote
}
